(with-open-file (my-stream "data.txt" :direction :output)
  (print "my data test" my-stream))
(with-open-file (my-stream "data.txt" :direction :input)
  (print (read my-stream)))
(defparameter my-socket (socket-server 4321))
(defparameter foo (make-string-output-stream))
(princ "This will go into foo." foo)
(princ "This will also go into foo." foo)
(get-output-stream-string foo)
